name : actiontest

on : push

env :
  IMAGE_NAME : julienmaalouf/action_test:test
  
jobs :
  build:
    runs-on: ubuntu-latest

    steps: 
      - uses :  actions/checkout@v2
      - name :  Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name : Push step
        run: |
          docker push $IMAGE_NAME
